spring:
  application:
    name: API Products
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
